[2024-01-31T21:37:29.123+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cleaning_data_final.trigger_second_dag manual__2024-01-31T21:36:38.375651+00:00 [queued]>
[2024-01-31T21:37:29.148+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cleaning_data_final.trigger_second_dag manual__2024-01-31T21:36:38.375651+00:00 [queued]>
[2024-01-31T21:37:29.149+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-31T21:37:29.175+0000] {taskinstance.py:2191} INFO - Executing <Task(TriggerDagRunOperator): trigger_second_dag> on 2024-01-31 21:36:38.375651+00:00
[2024-01-31T21:37:29.184+0000] {standard_task_runner.py:60} INFO - Started process 332 to run task
[2024-01-31T21:37:29.189+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cleaning_data_final', 'trigger_second_dag', 'manual__2024-01-31T21:36:38.375651+00:00', '--job-id', '552', '--raw', '--subdir', 'DAGS_FOLDER/Main_DAGS.py', '--cfg-path', '/tmp/tmpofbmd0bx']
[2024-01-31T21:37:29.194+0000] {standard_task_runner.py:88} INFO - Job 552: Subtask trigger_second_dag
[2024-01-31T21:37:29.226+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-01-31T21:37:29.323+0000] {task_command.py:423} INFO - Running <TaskInstance: cleaning_data_final.trigger_second_dag manual__2024-01-31T21:36:38.375651+00:00 [running]> on host e7e4b550b444
[2024-01-31T21:37:29.524+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cleaning_data_final' AIRFLOW_CTX_TASK_ID='trigger_second_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T21:36:38.375651+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T21:36:38.375651+00:00'
[2024-01-31T21:37:29.951+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/links/dataproc.py:79 AirflowProviderDeprecationWarning: This DataprocLink is deprecated.
[2024-01-31T21:37:29.954+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/links/dataproc.py:128 AirflowProviderDeprecationWarning: This DataprocListLink is deprecated.
[2024-01-31T21:37:31.487+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cleaning_data_final, task_id=trigger_second_dag, execution_date=20240131T213638, start_date=20240131T213729, end_date=20240131T213731
[2024-01-31T21:37:31.596+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-31T21:37:31.668+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
