[2024-01-31T20:03:44.623+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cleaning_data_final.trigger_second_dag manual__2024-01-31T20:02:59.399776+00:00 [queued]>
[2024-01-31T20:03:44.644+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cleaning_data_final.trigger_second_dag manual__2024-01-31T20:02:59.399776+00:00 [queued]>
[2024-01-31T20:03:44.645+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-31T20:03:44.676+0000] {taskinstance.py:2191} INFO - Executing <Task(TriggerDagRunOperator): trigger_second_dag> on 2024-01-31 20:02:59.399776+00:00
[2024-01-31T20:03:44.691+0000] {standard_task_runner.py:60} INFO - Started process 372 to run task
[2024-01-31T20:03:44.698+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cleaning_data_final', 'trigger_second_dag', 'manual__2024-01-31T20:02:59.399776+00:00', '--job-id', '432', '--raw', '--subdir', 'DAGS_FOLDER/Main_DAGS.py', '--cfg-path', '/tmp/tmpfyvhkpjk']
[2024-01-31T20:03:44.728+0000] {standard_task_runner.py:88} INFO - Job 432: Subtask trigger_second_dag
[2024-01-31T20:03:44.814+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-01-31T20:03:44.884+0000] {task_command.py:423} INFO - Running <TaskInstance: cleaning_data_final.trigger_second_dag manual__2024-01-31T20:02:59.399776+00:00 [running]> on host e7e4b550b444
[2024-01-31T20:03:45.010+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cleaning_data_final' AIRFLOW_CTX_TASK_ID='trigger_second_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T20:02:59.399776+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T20:02:59.399776+00:00'
[2024-01-31T20:03:45.624+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/links/dataproc.py:79 AirflowProviderDeprecationWarning: This DataprocLink is deprecated.
[2024-01-31T20:03:45.630+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/links/dataproc.py:128 AirflowProviderDeprecationWarning: This DataprocListLink is deprecated.
[2024-01-31T20:03:49.871+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cleaning_data_final, task_id=trigger_second_dag, execution_date=20240131T200259, start_date=20240131T200344, end_date=20240131T200349
[2024-01-31T20:03:49.988+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-31T20:03:50.033+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
