[2024-01-31T20:11:13.634+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cleaning_data_final.trigger_second_dag manual__2024-01-31T20:10:21.949333+00:00 [queued]>
[2024-01-31T20:11:13.649+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cleaning_data_final.trigger_second_dag manual__2024-01-31T20:10:21.949333+00:00 [queued]>
[2024-01-31T20:11:13.651+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-31T20:11:13.668+0000] {taskinstance.py:2191} INFO - Executing <Task(TriggerDagRunOperator): trigger_second_dag> on 2024-01-31 20:10:21.949333+00:00
[2024-01-31T20:11:13.678+0000] {standard_task_runner.py:60} INFO - Started process 854 to run task
[2024-01-31T20:11:13.683+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cleaning_data_final', 'trigger_second_dag', 'manual__2024-01-31T20:10:21.949333+00:00', '--job-id', '461', '--raw', '--subdir', 'DAGS_FOLDER/Main_DAGS.py', '--cfg-path', '/tmp/tmpez2ifzgf']
[2024-01-31T20:11:13.687+0000] {standard_task_runner.py:88} INFO - Job 461: Subtask trigger_second_dag
[2024-01-31T20:11:13.710+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-01-31T20:11:13.760+0000] {task_command.py:423} INFO - Running <TaskInstance: cleaning_data_final.trigger_second_dag manual__2024-01-31T20:10:21.949333+00:00 [running]> on host e7e4b550b444
[2024-01-31T20:11:13.866+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cleaning_data_final' AIRFLOW_CTX_TASK_ID='trigger_second_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T20:10:21.949333+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T20:10:21.949333+00:00'
[2024-01-31T20:11:14.070+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/links/dataproc.py:79 AirflowProviderDeprecationWarning: This DataprocLink is deprecated.
[2024-01-31T20:11:14.073+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/links/dataproc.py:128 AirflowProviderDeprecationWarning: This DataprocListLink is deprecated.
[2024-01-31T20:11:15.138+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cleaning_data_final, task_id=trigger_second_dag, execution_date=20240131T201021, start_date=20240131T201113, end_date=20240131T201115
[2024-01-31T20:11:15.198+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-31T20:11:15.233+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
